// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tBlock
{
    public int fBlockSId { get; set; }

    public string fMemberId { get; set; }

    public string fBlockUserId { get; set; }

    public string fBlockType { get; set; }
}