// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tComment
{
    public int fCommentId { get; set; }

    public int? fPostId { get; set; }

    public string fMemberId { get; set; }

    public string fContent { get; set; }

    public DateOnly? fCratedAT { get; set; }

    public DateOnly? fUpdateAt { get; set; }
}