// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tCustomerPreference
{
    public int fPreferId { get; set; }

    public string fMemberId { get; set; }

    public int fStockId { get; set; }
}