// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tCustomerStra
{
    public int fStraId { get; set; }

    public string fMemberId { get; set; }

    public int fStockId { get; set; }

    public decimal? fPriceSet { get; set; }

    public string fTranType { get; set; }

    public bool? fBuySell { get; set; }

    public decimal? f5MA { get; set; }

    public decimal? f10MA { get; set; }

    public decimal? f20MA { get; set; }

    public int? fKValue { get; set; }

    public int? fDValue { get; set; }
}