// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tFollower
{
    public int fFollowerSId { get; set; }

    public string fFollowerMemberId { get; set; }

    public string fFollowingMemberId { get; set; }
}