// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tGroupMember
{
    public int fGroupSId { get; set; }

    public string fMemberId { get; set; }

    public string fAccount { get; set; }

    public string fPassword { get; set; }

    public string fCorporation { get; set; }

    public string fEmail { get; set; }

    public string fRepresentName { get; set; }

    public string fCoLocation { get; set; }

    public string fUniBusinessNo { get; set; }

    public int? fTotalCapital { get; set; }

    public DateOnly? fRegDate { get; set; }

    public string fStatus { get; set; }

    public int? fPermissions { get; set; }

    public string fIp { get; set; }

    public byte[] fMemberImage { get; set; }

    public string fMemberImagePath { get; set; }
}