// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tHashtag
{
    public int fHashTagSId { get; set; }

    public string fHashTag { get; set; }

    public int? fPostId { get; set; }

    public string fMemberId { get; set; }

    public string fMemberType { get; set; }
}