// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tHelpMessageRecord
{
    public int fMessageRecord { get; set; }

    public int? fHelpId { get; set; }

    public string fContent { get; set; }

    public DateTime? fSendDate { get; set; }

    public int? fPublicOrNot { get; set; }
}