// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tHelp
{
    public int fHelpId { get; set; }

    public string fMemberId { get; set; }

    public int? fMemberType { get; set; }

    public string fName { get; set; }

    public string fPhone { get; set; }

    public string fNId { get; set; }

    public int? fTaxID { get; set; }

    public int? fDistrictId { get; set; }

    public string fHelpDescribe { get; set; }

    public int? fHelpClassId { get; set; }

    public int? fHelpSkillId { get; set; }

    public int? fHelpStatus { get; set; }

    public DateTime? fMfdDate { get; set; }

    public DateTime? fExpDate { get; set; }
}