// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tInvestRecord
{
    public int fRepoId { get; set; }

    public string fMemberId { get; set; }

    public DateTime fStartDate { get; set; }

    public DateTime fEndDate { get; set; }

    public int fStockId { get; set; }

    public DateTime? fSoldTime { get; set; }

    public decimal fCost { get; set; }

    public decimal fDealPrice { get; set; }

    public int fStockQty { get; set; }

    public double fProSum { get; set; }

    public double fProTSum { get; set; }
}