// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tLike
{
    public int fLikesSId { get; set; }

    public string fUserId { get; set; }

    public string fPostId { get; set; }

    public string fTimestamp { get; set; }
}