// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tLoginRecord
{
    public int fLogId { get; set; }

    public string fMemberId { get; set; }

    public byte[] fTimestamp { get; set; }

    public string fIp { get; set; }
}