// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tMatch
{
    public int fMatchId { get; set; }

    public int? fHelpId { get; set; }

    public string fMemberId { get; set; }

    public DateTime? fMatchDateTime { get; set; }

    public int? fPoint { get; set; }

    public int? fMatchStatus { get; set; }

    public int? fGrade { get; set; }

    public DateTime? fGradeDateTime { get; set; }

    public string fMessage { get; set; }
}