// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tMessage
{
    public int fMessid { get; set; }

    public string fSId { get; set; }

    public string fRId { get; set; }

    public string fMessContent { get; set; }

    public byte[] fTimestamp { get; set; }
}