// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tMgrScFile
{
    public int fFileId { get; set; }

    public string fMemberId { get; set; }

    public string fFileName { get; set; }

    public string fFilePath { get; set; }

    public string fFileType { get; set; }

    public byte[] fUploadateAt { get; set; }
}