// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tOrder
{
    public int fOrderId { get; set; }

    public string fMemberId { get; set; }

    public int? fTotalHelpPoint { get; set; }

    public int? fStatus { get; set; }

    public DateTime? fOrderTime { get; set; }

    public int? fExecStatus { get; set; }

    public DateTime? fBeginTime { get; set; }

    public DateTime? fFinishTime { get; set; }

    public byte[] fProof { get; set; }
}