// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tOrderDetail
{
    public int fOrderDetailId { get; set; }

    public int fOrderId { get; set; }

    public int? fProductId { get; set; }

    public int? fAmount { get; set; }

    public int? fHelpPoint { get; set; }
}