// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tPersonMember
{
    public int fPersonSId { get; set; }

    public string fMemberId { get; set; }

    public string fAccount { get; set; }

    public string fPassword { get; set; }

    public string fUserName { get; set; }

    public string fFirstName { get; set; }

    public string fLastName { get; set; }

    public string fEmail { get; set; }

    public string fIdentification { get; set; }

    public DateOnly? fBirthDate { get; set; }

    public string fSex { get; set; }

    public DateOnly? fRegDate { get; set; }

    public int? fTotalHelpPoint { get; set; }

    public int? fTotalAsset { get; set; }

    public int? fDistrictId { get; set; }

    public string fStatus { get; set; }

    public int? fPermissions { get; set; }

    public string fIp { get; set; }

    public byte[] fMemberImage { get; set; }

    public string fMemberImagePath { get; set; }
}