// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tPointList
{
    public int fPointListId { get; set; }

    public string fMemberId { get; set; }

    public int? fMatchId { get; set; }

    public int? fOrderId { get; set; }

    public int? fSourse { get; set; }

    public DateTime? fRecordTime { get; set; }
}