// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tPost
{
    public int fPostId { get; set; }

    public string fMemberId { get; set; }

    public string fUserName { get; set; }

    public string fPostContent { get; set; }

    public int? fLikes { get; set; }

    public byte[] fTimestamp { get; set; }

    public string fMemberType { get; set; }

    public int? fParentCommentId { get; set; }

    public byte[] fFinStatement { get; set; }
}