// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tProductCategory
{
    public int fProductCategoryId { get; set; }

    public string fProductCategoryName { get; set; }

    public string fDescription { get; set; }
}