// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tProduct
{
    public int fProductId { get; set; }

    public int fProductCategoryId { get; set; }

    public int? fSponsorId { get; set; }

    public string fProductName { get; set; }

    public string fDescription { get; set; }

    public int? fSales { get; set; }

    public int? fStock { get; set; }

    public int? fUnitlHelpPoint { get; set; }

    public int? fStatus { get; set; }
}