// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tSponsorCategory
{
    public int fSponsorCategoryId { get; set; }

    public string fSponsorCategoryrName { get; set; }

    public string fDescription__fDescription { get; set; }
}