// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tSponsor
{
    public int fSponsorId { get; set; }

    public string fSponsorName { get; set; }

    public int? fSponsorCategoryId { get; set; }

    public string fAddress { get; set; }

    public string fPhone { get; set; }

    public decimal? fCapital { get; set; }

    public string fIntroduction { get; set; }

    public int? fStatus { get; set; }
}