// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tStockInStock
{
    public string fMemberId { get; set; }

    public string fBrokerId { get; set; }

    public int fStockId { get; set; }

    public string fStockName { get; set; }

    public string fTranType { get; set; }

    public int? fLeftStock { get; set; }

    public int? fStockAdj { get; set; }

    public int? fStockNow { get; set; }

    public int? fStockTran { get; set; }

    public decimal? fStockPriceN { get; set; }

    public decimal? fStockPriceT { get; set; }

    public decimal? fStockPriceTS { get; set; }

    public decimal? fStockCost { get; set; }

    public decimal? fEstPro { get; set; }

    public double? fEstProP { get; set; }

    public decimal? fBalancePrice { get; set; }
}