// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tStock
{
    public int fStockId { get; set; }

    public string fStockName { get; set; }

    public decimal? fStockPriceN { get; set; }
}