// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class TStock
{
    public int FStockId { get; set; }

    public string FStockName { get; set; }

    public decimal? FStockPriceN { get; set; }
}