// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Final10._14.Models;

public partial class tTranRecord
{
    public int fTranId { get; set; }

    public string fMemberId { get; set; }

    public int fStockId { get; set; }

    public string fBrokerId { get; set; }

    public string fTranType { get; set; }

    public string fBuySell { get; set; }

    public int fStockQty { get; set; }

    public decimal fStockPrice { get; set; }

    public DateTime fTranTime { get; set; }
}